/**
 * Platform abstraction for all cryptographic primitives. The production implementation uses
 * WebCrypto (available on Obsidian desktop and mobile). No primitive is implemented by hand.
 */

export type AeadAlgorithm = "AES-256-GCM";

export interface EncryptedData {
  readonly algorithm: AeadAlgorithm;
  /** 96-bit nonce, freshly generated by the provider for every encryption. */
  readonly nonce: Uint8Array;
  /** Ciphertext with the 128-bit authentication tag appended. */
  readonly ciphertext: Uint8Array;
}

export interface CryptoProvider {
  /** Cryptographically secure random bytes. */
  randomBytes(length: number): Uint8Array;

  /** Imports 32 raw bytes as a non-extractable AES-256-GCM key. */
  importAeadKey(raw: Uint8Array): Promise<CryptoKey>;

  /**
   * Authenticated encryption. The nonce is generated inside the provider so callers can never
   * reuse one by accident.
   */
  encrypt(plaintext: Uint8Array, key: CryptoKey, associatedData: Uint8Array): Promise<EncryptedData>;

  /** Authenticated decryption; throws CryptoError("DecryptionFailed") on any authentication failure. */
  decrypt(data: EncryptedData, key: CryptoKey, associatedData: Uint8Array): Promise<Uint8Array>;

  /** SHA-256 as lowercase hex. */
  hash(data: Uint8Array): Promise<string>;

  sha256(data: Uint8Array): Promise<Uint8Array>;

  hkdfSha256(ikm: Uint8Array, salt: Uint8Array, info: Uint8Array, length: number): Promise<Uint8Array>;

  hmacSha256(key: Uint8Array, data: Uint8Array): Promise<Uint8Array>;

  pbkdf2Sha256(password: Uint8Array, salt: Uint8Array, iterations: number, length: number): Promise<Uint8Array>;
}
